### ISSUE TITLE
Raise Error when status >300

### ISSUE THREAD

**Issue by zhongwencool** [zhongwencool/maxwell#15]
## Now:
it will raise  Maxwell.Error when middleward return {:error, reason}.
```ex
def unquote(method_exception)(conn \\ %Maxwell.Conn{})
def unquote(method_exception)(conn) do
          case unquote(method)(conn) do
            {:ok, %Maxwell.Conn{} = result} ->
              result
            {:error, reason}  ->
              raise Maxwell.Error, value: reason,
                message: "method: #{unquote(method)} reason: #{inspect reason} url: #{conn.url}, module: #{__MODULE__}"
          end
        end
```
## New:
```ex
def unquote(method_exception)(conn \\ %Maxwell.Conn{}, exclude_status_list\\[])
def unquote(method_exception)(conn, exclude_status_list) do
     case unquote(method)(conn) do
         {:ok, %Maxwell.Conn{status = status} = result} ->
            if (status < 300 or status in exclude_status_list), do: raise Maxwell.ResponseError, status: status, message: "method: #{unquote(method)} reason: #{inspect body} url: #{conn.url}
          result
       {:error, reason}  ->
           raise Maxwel.RequestError, value: reason,
                message: "method: #{unquote(method)} reason: #{inspect reason} url: #{conn.url}, module: #{__MODULE__}"
      end
  end
```

Add new exception: `Maxwell.ResonseError`   `Maxwell.ResquestError`

Maybe you have better name for the new exceptions @secretworry?

**Comment by secretworry** [comment]
The convention would be creating two methods, the normal one, which returns `{:ok, conn} | {:error, error_t}`, and the bang(!) one, which returns `conn` or raises an error.

I don't think we have enough reason to make a distinction between `Maxwell.RepsonseError` and `Maxwell.ResquestError`, cuz, the information they can carry are all derived from the `conn`, which makes them identical to each other. Besides, the distinction doesn't make handling them any easier.

So my advice is to normalize the format of `error_t` as `{reason, conn}` , so the user can get not only the reason but all the information needed to handle the error.

As for the bang version, we should just create an error that can simplify accessing attributes on `conn`( and, of course, we should carry back the conn itself too) and carry a human-readable error message. So something like:

`%Maxwell.RequestError{url: String.t, method: String.t, reason: atom, message: String.t, msgid: String.t, bindings: Map.t, status: int | nil, conn: Maxwell.Conn.t}`

* `url` - the request url
* `method` - the request method
* `status` - response status if any
* `reason` - the reason causing the error
* `message` - interpolated human readable message for describing error
* `msgid` - the raw message not interpolated (e.g. "Illegal response status: %{status}")
* `bindings` - bindings for interpolating msgid (e.g, %{status: 100})
* `conn` - the `Maxwell.Conn` gone through the middleware

**Comment by zhongwencool** [comment]
https://github.com/zhongwencool/maxwell/pull/16
