### ISSUE TITLE
Need more documentation on middleware

### ISSUE THREAD

**Issue by imranismail** [zhongwencool/maxwell#26]
I need to implement a rate limiter middleware akin to this but on the Connection level instead of per function.

Is it possible with middleware.. or is the middleware just for composing the connection struct?

```elixir
defmodule Shopify.Product do
  import Maxwell.Conn

  def stream!(client, opts \\ []) do
    query_params =
      opts
      |> Enum.into(%{})
      |> Map.put_new(:page, 0)
      |> Map.put_new(:limit, 50)

    start = fn -> {query_params, []} end

    next = fn {query_params, accumulator} ->
      query_params = Map.update!(query_params, :page, &(&1 + 1))

      start_timestamp = DateTime.utc_now() |> DateTime.to_unix(:millisecond)

      client =
        client
        |> put_path("/products")
        |> put_query_string(query_params)
        |> get!()

      finish_timestamp = DateTime.utc_now() |> DateTime.to_unix(:millisecond)

      duration = finish_timestamp - start_timestamp

      throttle? =
        client
        |> get_resp_header()
        |> Map.get("X-Shopify-Shop-Api-Call-Limit")
        |> Kernel.==("40/40")

      if throttle?, do: Process.sleep(duration)

      client
      |> get_resp_body("products")
      |> case do
        [] ->
          {:halt, accumulator}
        products ->
          {products, {query_params, Enum.concat(accumulator, products)}}
      end
    end
end
```

**Comment by secretworry** [comment]
The API for middleware is quite simple, `call(conn, next, opts)`. `conn` is the connection, `next` is a 1-arity function used to make the process continue. the pseudo code implementing the similar function for given sample is like following:
```elixir
defmodule Throttle do
   use Maxwell.Middleware
   def call(conn, next, opts) do
      :ok = case throttle(conn, opts) do # implement throttle/2 according to your logic
         delay when delay > 0 -> Process.sleep(duration)
         true -> :ok
      end
      next.(conn) # continue the process
   end
end
```

**Comment by imranismail** [comment]
Thanks, I see what the second arg is used for! Interesting API

**Comment by imranismail** [comment]
@secretworry I'm trying to understand, how is it that multiple middlewares can call the `next.()` function?

For example logger invokes the `next.()` and my middleware invokes the `next.()` as well. How does it work?

**Comment by bitwalker** [comment]
@imranismail If you define middlewares like so:

```elixir
defmodule MyClient do
  use Maxwell.Builder
  middleware A
  middleware B
  middleware C
  adapter Maxwell.Adapter.Httpc
end
```

This is transformed into a chain like so:

```elixir
A.call(conn, fn conn -> 
  B.call(conn, fn conn -> 
    C.call(conn, fn conn -> 
      Maxwell.Adapter.Httpc.call(conn) 
    end, c_opts)
  end, b_opts),
end, a_opts)
```

I've omitted some extra steps here, which simply check to see if `conn` is an error tuple, and
returns it directly if it is, otherwise calling the next middleware if the previous succeeded. When this pipeline is executed, the following occurs:

- A calls `next.(conn)` calling B, 
- B calls `next.(conn)`, calling C,
- C calls `next.(conn)`, which calls the adapter
- The adapter makes the request, and returns the connection to C
- C calls `response` and returns to B
- B calls `response` and returns to A
- A calls `response` and returns to the caller

Does that help?

**Comment by imranismail** [comment]
@bitwalker splendid!

It's slightly different than plug in a sense that it'll callback the response function. Thanks for clearing this up.

**Comment by bitwalker** [comment]
@imranismail Oh, the response function is part of the middleware itself, each middleware calls it's request function, then next, then response by default or if you only override request or response. If you override call, then it is up to you how it works.

**Comment by imranismail** [comment]
I see, wow this is pretty nice. Can hook into after/before or just as a pass through middleware.

Thanks again!
