### ISSUE TITLE
Internal consistency issues

### ISSUE THREAD

**Issue by bitwalker** [zhongwencool/maxwell#30]
Even though Maxwell has 100% test coverage, it's clear the interaction between some things is not tested. Namely the combination of some middlewares. This also lead me to discover that the typespecs/return values in the `Middleware` behaviour do not match what is actually expected by Maxwell's code internally. An example:

```elixir
defmodule TestClient do
  use Maxwell.Builder
  middleware Maxwell.Middleware.BaseUrl, "http://google.com"
  middleware Maxwell.Middleware.Logger, log_level: :debug
  adapter Maxwell.Middleware.Httpc

  def explodes(path) do
    get!(path)
  end
end

TestClient.explodes("/")
** (exit) an exception was raised:
    ** (CaseClauseError) no case clause matching: %Maxwell.Conn{...}
        (testapp) lib/maxwell/builder.ex:5: TestClient.get!/1
```

The above error led me to look at how middlewares were returning, and many of them just pass along (unmatched) anything which isn't an error tuple. However some middlewares, namely `Logger`, actually expect call/request/response to return `{:ok, Maxwell.Conn.t}`, as does `Maxwell.Builder` from what I can tell, but the `BaseUrl` middleware returns `Maxwell.Conn.t`.

From what I can tell, all middlewares should be returning `{:ok, Maxwell.Conn.t}`, but the `Maxwell.Middleware` behaviour specifies only `Maxwell.Conn.t` in it's callback specification. In other words, something is broken and needs to be fixed, but it's not clear what. The code says one thing, the typespecs another, and things explode at runtime even though all the tests pass. Clearly some richer integration tests are required to really ensure things play nice together.

I'm going to fix things in a PR so that all middlewares return `Maxwell.Conn.t`, and update the typespecs. If that's not the desired path, just let me know.

**Comment by zhongwencool** [comment]
Thanks for this big change。

**Comment by bitwalker** [comment]
You bet :)
