### ISSUE TITLE
Introduce :private in Maxwell.Conn struct

### ISSUE THREAD

**Issue by imranismail** [zhongwencool/maxwell#35]
For example there are use cases where I need a `raw_body` instead of a decoded one, I don't want to encode it back to json since it's expensive.

Instead I want to add a middleware that populates the `:private` map in conn struct with `raw_body`

and let the json middleware do it's job.

Can we introduce a `:private` attribute in `Maxwell.Conn` for this?

additional suggested functions to add to `Maxwell.Conn`

`get_private/2`
`put_private/3`

**Comment by bitwalker** [comment]
I'm 👍 on this. I can get this implemented this week.

**Comment by imranismail** [comment]
@bitwalker can I handle this one? It's pretty simple 😄

**Comment by bitwalker** [comment]
Sure thing :), though you may want to wait until #36 is merged, because that PR updates the internals a bit, and it'll save you some hassle rebasing later on.

**Comment by imranismail** [comment]
Yeap, I'm watching that PR. Thanks!
