### ISSUE TITLE
The header middleware should just provides default headers instead of overriding the provided ones

### ISSUE THREAD

**Issue by secretworry** [zhongwencool/maxwell#40]
The header middleware is just `put_req_headers` into the `conn`, which will make the user-provided headers be overridden.

Besides, we may need to create a `Headers` module to dealing with adding, getting and merging headers in the `Conn`. So that, we don't need to new a `Conn` to operate with headers(as we are doing in the `init/1` of Header middleware)

**Comment by zhongwencool** [comment]
I can fix it.
Adding, getting and merging headers in the `Conn` is only `Map` operation.
It's too simple. I don't think we should create a new module, just don't worth even implement by inline function.

**Comment by bitwalker** [comment]
Fixed by #42
