### ISSUE TITLE
graphql and/or falcor json graph

### ISSUE THREAD

**Issue by niccolox** [zhongwencool/maxwell#43]
hey there

am doing research and trying to find alternatives to Graphql and am drawing a blank

seems to me that layer or implementation could be built on top of Maxwell, perhaps using Netflix's JSON Graph or some other kind of JSON API query language

I dont want to use GraphQL because of the PATENTS extras 

I asked a question of Poison creator https://github.com/devinus/poison/issues/116

**Comment by bitwalker** [comment]
This is an HTTP client library, what exactly is the question and/or proposal here?

**Comment by niccolox** [comment]
my understanding is that the heart of this library is the querying and decoding of json api and other http endpoints, this is what GraphQL also does, in a different way

https://github.com/zhongwencool/maxwell/blob/master/test/maxwell/middleware/base_url_test.exs#L20


one question is, would it make sense to create json query language dsl that creates an abstraction layer above Maxwell ?

if so, what alternatives to GraphQL are out there?

I know this is an open question, I am trying to get a sense of thinking on this area

I read the Tesla vs Maxwell thread and I thought I'd ask around and try to connect and get a conversation started

**Comment by bitwalker** [comment]
My impression is that GraphQL and the like reside a level above HTTP clients, at the end of the day though, a GraphQL request is executed just like any other JSON API request, there isn't anything special done at the HTTP client level. Given that, I don't see what Maxwell can provide to make GraphQL or similar implementations, easier to produce, that it doesn't already provide today.

**Comment by niccolox** [comment]
thanks for taking the time to discuss this and clarify project scope etc

I am going to try to find an alternative spec to GraphQL because of PATENTS and the Netflix Falcor thing looks too complicated

if I can find an alternative json api query spec I'll try to implement it and maybe write a DSL / macro and use Maxwell, Poison etc for middleware etc

it would be great if you could leave this thread open for others who might have something to contribute

one of the issues with having a million projects on github for Elixir is this fragmentation and the nano-project tendency a la Nodejs

interesting background article https://www.programmableweb.com/news/just-because-github-has-graphql-api-doesn%E2%80%99t-mean-you-should-too/analysis/2016/09/21

**Comment by bitwalker** [comment]
While I think this is a good discussion, I think it would be best moved to [ElixirForum](https://elixirforum.com) as it doesn't pertain specifically to this project and that is a more appropriate forum for this topic. I'm going to close this for now, but others are free to add comments.
