### ISSUE TITLE
[QUESTION] HTTP method return value for errors

### ISSUE THREAD

**Issue by visciang** [zhongwencool/maxwell#66]
Just looking at the code.
Do we need the clause `{:error, _}` at [L172](https://github.com/zhongwencool/maxwell/blob/master/lib/maxwell/builder.ex#L172) and [L183](https://github.com/zhongwencool/maxwell/blob/master/lib/maxwell/builder.ex#L183)?

We should have only `{:error, reason, %Maxwell.Conn{}}`

**Comment by secretworry** [comment]
@visciang actually, we just had the `{:error, reason}` at first. Considering the error handler may need to retrieve some props from the `%Maxwell.Conn{}`, we added the conn to the error type.

In short, consider it as a forwards compatibility feature.
