### ISSUE TITLE
Maxwell.Multipart.add_file* extension

### ISSUE THREAD

**Issue by visciang** [zhongwencool/maxwell#69]
I'm using `Maxwell.Multipart.add_file_with_name` to build a multipart body.
Currently, all `Maxwell.Multipart.add_file` `Maxwell.Multipart.add_file_with_name` functions require the file input parameter as a `Path.t` (a path pointing to an existing file on the filesystem)

`@spec add_file(t, Path.t) :: t`

I would like to extend this API to accept also the file content binary. In my application the content to send is in memory (retrieved from an external source, ex. DB or cache) and now I have to write the binary to a temporary file and pass the path to the `Maxwell.Multipart.add_file` function.

If you think this is welcome I can open a PR, just tell me what are your preferences.

For example, we could add `Maxwell.Multipart.add_file_content` `Maxwell.Multipart.add_file_content_with_name`.

**Comment by zhongwencool** [comment]
`Maxwell.Multipart.add_file_content_with_name`  is ok for me.
Sorry for being late and appreciate your PR.

**Comment by visciang** [comment]
Coming soon!
Thank you

**Comment by zhongwencool** [comment]
@visciang Thanks a lot 👍
